mozilla/coverage-crawler

.isort.cfg
crawler.py
requirements-test.txt
requirements.txt

Adds flake8-isort 2.4

---

README.md

Fixes #15. 
I have, finally, solved the problem with commits. :)

updated README.md 

---

latest_cov_build.py

I have used taskId from Taskcluster Index API to download the required components relevant to the latest build we use. 
Fixes #22.

Download gcno archive and chrome-map.json automatically

---

crawler.py

Environment variable for JS engine to emit JS coverage information

---

crawler.py

Issue #2 
I have made parsing of .gcda files stored in the temporary GCOV directory to store coverage information in `coveralls.json` file with grcov. Used subprocesses to call the shell command in the script and to output the result to `coveralls.json`. Shutil module was used to zip .gcda files.
I am not sure how to check whether the generated report (coveralls.json) is right. Can you suggest a way? I have added it to the commit too.

grcov parsing of gcda files 

---

crawler.py
latest_cov_build.py
test-requirements.txt

Fixes #40.
Added flake8 modules and checked code with them.

flake8 modules added

---

latest_cov_build.py

Change latest.firefox.linux64-ccov-opt to latest.firefox.linux64-ccov-debug

---

.isort.cfg
crawler.py

Modify .isort.cfg to force single line imports

---

crawler.py
websites.txt

Fixes #52 
List of websites the crawler has to start is read from `websites.txt` file.

List of websites the crawler has to start

---

crawler.py

Use grcov's '--filter covered' option

---

.gitignore
crawler.py

Fixes #61 
I've also changed `.gitignore` not to commit files that are generated by crawler.

Support submit input type

---

diff.py
test/test_diff.py

Fixes #57 
It somehow decreased the size of diff report. :)

Clean coverage list if equal in baseline report and report

---

crawler.py
diff.py
test/test_diff.py

Add option to ignore hit counts

---

.gitignore

Add files generated by the crawler to .gitignore

---

crawler.py

Fixes #53 
I also added some more input types and ScrollIntoView [I've used those from `autowebcompat ` :)] to this PR as I think they are relevant to making it crawl more without exceptions. :)

Make crawler crawl more

---

latest_cov_build.py

Don't unzip and remove archive with gcno files

---

crawler.py
latest_cov_build.py

Parse JavaScript coverage

---

crawler.py
generatehtml.py
latest_cov_build.py

Fixes #58 
I've made it in Python instead of working with https://github.com/marco-c/grcov/issues/94 but I can try to change it later. 
The report is now generated in the folder that contains `diff.json` file.

Generate HTML report from JSON report

---

latest_cov_build.py

Fixes #75 
Made it be an optional command-line argument.

Added optional revision command-line argument

---

crawler.py

Fixes #78 
I was encountering "Element is not clickable at point <x, y> as it is obscured" exception, and as a solution, I found that we need to ensure that zoom is on 100%. And, I changed the place of the try-catch block in for loop in order to allow the crawler to finish crawling and writing to file if it encounters an exception.

Exceptions handling

---

crawler.py

Fixes #85 
I've added `dialog`, `frame` tag names and `reset` input type. 
Tried running with 50 steps and it worked well, ignoring exceptions and adding obscured elements to the global set of `not_clickable_elems`.

Add exception checking and more features

---

generatehtml.py
style.css

Add CSS file and option to use it

---

generatehtml.py
latest_cov_build.py

Fixes #96 
I've made it be downloaded in `latest_cov_build.py` with all other artifacts

Download genhtml once

---

crawler.py

Prefer not used elements

---

requirements.txt

To use it with `lcov_rewriter.py`.

Add six library to requirements

---

setup.py

Make crawler installable

---

.travis.yml
test-requirements.txt

Add test for installing the package

---

setup.py

Add license

---

coverage_crawler/crawler.py
run_crawler.py

Fixes #120 
Now, it accepts URL and returns a path to the folder with generated HTML report.
Probably, I can add GitHub upload functionality in the `crawler.py` file itself?

Make crawler modular

---

requirements.txt

Update firefox-code-coverage dependency

---

requirements.txt
test-requirements.txt

Fixes #140 
Travis is happy with this. :)

Update attrs version to use with 3.7.* versions of pytest

---

README.md

Added Python 3.6+ and Mercurial to software requirements in README.md

---

requirements.txt

Rollback taskcluster from 5.0.0 to 4.0.1

---

test-requirements.txt

remove attrs requirement

---

coverage_crawler/crawler.py
requirements.txt
test-requirements.txt
tests/crawler/test_crawler_unittest.py
tests/example_website/templates/index.html
tests/example_website/website_app.py

test `find_children` using flask server

---

tests/crawler/test_crawler_unittest.py
tests/example_website/templates/index.html

add `test_get_all_attributes`

---

coverage_crawler/crawler.py

selenium was bumped from version 3 to 4, which caused the syntax we use in `crawler.py` to become incorrect.
now it works :)

fix `find_elements` syntax

---

requirements.txt

remove git link from requirements.txt
